#!/bin/bash

###############################################################################
#                            Arguments, fixed                                  #
###############################################################################
tmpdir="$1"
basename="$2"

scriptsdir=../scripts
srcdir=../src

asmfile=$tmpdir/$basename.s43


incfilev="$tmpdir/sancus-core-gap/core/rtl/verilog/openMSP430_defines.v";
incfile=$tmpdir/pmem.h

linkfile="$tmpdir/sancus-core-gap/core/sim/rtl_sim/bin/template.x";
# linkfile=$scriptsdir/template.x;
headfile="$tmpdir/sancus-core-gap/core/sim/rtl_sim/bin/template_defs.asm"
#headfile=$scriptsdir/template_defs.asm;
sancus_macro="sancus_macros.asm"

# Copy necessary files
cp $srcdir/$sancus_macro $tmpdir/$sancus_macro
cp $asmfile $tmpdir/pmem.s43
cp $scriptsdir/omsp_config.sh $tmpdir/omsp_config.sh

cp $incfilev  $incfile
sed -i 's/`ifdef/#ifdef/g'   $incfile
sed -i 's/`ifndef/#ifndef/g' $incfile
sed -i 's/`else/#else/g'     $incfile
sed -i 's/`endif/#endif/g'   $incfile
sed -i 's/`define/#define/g' $incfile
sed -ie 's/`include/\/\/#include/g' $incfile
sed -i 's/`//g'              $incfile
sed -i "s/'//g"              $incfile

# Use MSPGCC preprocessor to extract the Program, Data
# and Peripheral memory sizes
if command -v msp430-gcc >/dev/null; then
    msp430-gcc -E -P -x c $tmpdir/omsp_config.sh > $tmpdir/pmem.sh
else
    msp430-elf-gcc -E -P -x c $tmpdir/omsp_config.sh > $tmpdir/pmem.sh
fi

# Source the extracted configuration file
source $tmpdir/pmem.sh

# Compile assembler code
echo "Compile, link & generate IHEX file (Program Memory: $pmemsize B, Data Memory: $dmemsize B, Peripheral Space: $persize B)..."
$scriptsdir/asm2ihex.sh $tmpdir/pmem $tmpdir/pmem.s43 $linkfile $headfile $pmemsize $dmemsize $persize "$tmpdir"

# # Generate Program memory file
echo "Convert IHEX file to Verilog MEMH format..."
$scriptsdir/ihex2mem.tcl -ihex $tmpdir/pmem.ihex -out $tmpdir/$basename.mem -mem_size $pmemsize

