#!/bin/bash
tmpdir="$1"
basename="$2"

precompiled=$tmpdir/$basename.mem
expectedpmem=$tmpdir/pmem.mem
simexec=sancus-core-gap/obj_dir/simv

echo "Copying: $expectedpmem -> $precompiled"
cp $precompiled $expectedpmem

echo "Simulating: $basename > $tmpdir/tb_openMSP430.vcd"
# simout=$(cd $tmpdir; vvp -n $simexec)
simout=$(cd $tmpdir; $simexec)
exit_code=0
motivation=""

if grep -q "SIMULATION FAILED" <<< "$simout"; then
    if grep -q "the verilog stimulus didn't complete" <<< "$simout"; then
        exit_code=1
        motivation="Verilog stimulus not complete"
    elif grep -q "simulation Timeout" <<< "$simout"; then
        exit_code=2
        motivation="Timeout"
    else
        exit_code=3
        motivation="$simout"
    fi
    echo "Simulation: fail ($exit_code - $motivation)"
else
    echo "Simulation: success"
fi

exit $exit_code
